#!/usr/bin/python

import sys

if __name__ == '__main__':
    fname = sys.argv[1]
    with open(fname) as f:
        #assume file is in correct format
        number = int(f.read().strip())
    
    for i in range(1, number+1):
        if i % 15 == 0:
            print 'Hop'
        elif i % 3 == 0:
            print 'Hoppity'
        elif i % 5 == 0:
            print 'Hophop'

